name: 'Merge Checker'
on:
  workflow_call:
    inputs:
      needs:
        type: string
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check needs
        run: echo "${NEED_CONTEXT}" | jq --exit-status 'all(.. | .result? | strings | . == "success")'
        env:
          NEED_CONTEXT: ${{inputs.needs}}
