name: 'Release Prod Gradle'
on:
  workflow_call:
    inputs:
      sign_check_command:
        type: string
        required: false
        default: ''
      release_command:
        type: string
        required: true
      enable_signature_check:
        type: boolean
        default: false
      use_gradle_cache:
        type: boolean
        default: false
      java_version:
        type: string
        default: '17'
    secrets:
      GCP_IDENTITY_PROVIDER:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      GCP_VERSION_FUNCTION_ENDPOINT:
        required: true
      GCP_FUNCTION_EXECUTION_ACCOUNT:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      DISABLE_EXAMPLE: true
    permissions:
      id-token: write
      contents: write
      packages: write
      attestations: write
      artifact-metadata: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: gradle/actions/wrapper-validation@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: ${{inputs.java_version}}
      - uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          cache-disabled: ${{!inputs.use_gradle_cache}}
          cache-read-only: true
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{secrets.GCP_IDENTITY_PROVIDER}}
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}
      - name: Create Temporary Directory
        id: tmp-dir
        run: |
          TMP_DIR="$(mktemp -d)"
          echo "path=${TMP_DIR}" >> "$GITHUB_OUTPUT"
      - name: Download Private Key
        run: gcloud storage cp gs://kotori316-resources/secring.gpg "${{ steps.tmp-dir.outputs.path }}/secring.gpg"
      - name: Download JKS
        run: gcloud storage cp gs://kotori316-resources/kotori316_keystore.jks "${{ steps.tmp-dir.outputs.path }}/kotori316_keystore.jks"
      - name: Download Public Key
        run: |
          gcloud storage cp gs://kotori316-resources/pgp_public.pub "${{ steps.tmp-dir.outputs.path }}/pgp_public.pub"
          gpg --import "${{ steps.tmp-dir.outputs.path }}/pgp_public.pub"
      - name: Get credentials
        id: get-secrets
        uses: google-github-actions/get-secretmanager-secrets@bc9c54b29fdffb8a47776820a7d26e77b379d262 # v3.0.0
        with:
          secrets: |-
            key_id:kotori316-mods-resources/signing-key-id
            key_password:kotori316-mods-resources/signing-password
            jar_password:kotori316-mods-resources/jar-sign-key-password
            modrinth_token:kotori316-mods-resources/modrinth_token
            curseforge_token:kotori316-mods-resources/curseforge_token
            cloudflare_s3_endpoint:kotori316-mods-resources/cloudflare_s3_endpoint
            cloudflare_access_key:kotori316-mods-resources/cloudflare_access_key
            cloudflare_secret_key:kotori316-mods-resources/cloudflare_secret_key
            repolisite-publisher-name:kotori316-mods-resources/repolisite-publisher-name
            repolisite-publisher-password:kotori316-mods-resources/repolisite-publisher-password
      - run: chmod +x ./gradlew
      - name: Check build with sign arguments
        if: inputs.sign_check_command != ''
        run: >-
          ./gradlew
          -Psigning.secretKeyRingFile="${{ steps.tmp-dir.outputs.path }}/secring.gpg"
          -Psigning.password="${KEY_PASSWORD}"
          -Psigning.keyId="${KEY_ID}"
          -PjarSign.keyLocation="${{ steps.tmp-dir.outputs.path }}/kotori316_keystore.jks"
          -PjarSign.keyAlias="ko316"
          -PjarSign.storePass="${JAR_PASSWORD}"
          ${{inputs.sign_check_command}}
        env:
          KEY_PASSWORD: ${{steps.get-secrets.outputs.key_password}}
          KEY_ID: ${{steps.get-secrets.outputs.key_id}}
          JAR_PASSWORD: ${{steps.get-secrets.outputs.jar_password}}
      - name: Verify
        if: inputs.sign_check_command != '' && inputs.enable_signature_check
        run: |
          for f in $(find ./ -name "*.asc") ; do
            echo "::group::Build ${f:0:-4}"
            gpg --verify "$f" "${f:0:-4}"
            echo "::endgroup::"
          done
          for f in $(find . ! -name '*deobf.jar' ! -name '*sources.jar' ! -name '*common.jar' ! -name '*dev.jar' ! -path '*/common/*' -path '*/build/libs/*' -name '*.jar') ; do
            echo "::group::Jar sign ${f}"
            jarsigner -verify -keystore "${{ steps.tmp-dir.outputs.path }}/kotori316_keystore.jks" "$f"
            echo "::endgroup::"
          done
          for f in $(find ~/.m2 -name "*.asc") ; do
            echo "::group::${f:0:-4}"
            echo "${f:0:-4}"
            gpg --verify "$f" "${f:0:-4}"
            echo "::endgroup::"
          done
      - name: Release
        run: >-
          ./gradlew
          -Psigning.secretKeyRingFile="${{ steps.tmp-dir.outputs.path }}/secring.gpg"
          -Psigning.password="${KEY_PASSWORD}"
          -Psigning.keyId="${KEY_ID}"
          -PjarSign.keyLocation="${{ steps.tmp-dir.outputs.path }}/kotori316_keystore.jks"
          -PjarSign.keyAlias="ko316"
          -PjarSign.storePass="${JAR_PASSWORD}"
          -Dorg.gradle.s3.endpoint="${CLOUDFLARE_S3_ENDPOINT}"
          ${{inputs.release_command}}
        env:
          RELEASE_DEBUG: false
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
          KEY_PASSWORD: ${{steps.get-secrets.outputs.key_password}}
          KEY_ID: ${{steps.get-secrets.outputs.key_id}}
          JAR_PASSWORD: ${{steps.get-secrets.outputs.jar_password}}
          CURSE_TOKEN: ${{steps.get-secrets.outputs.curseforge_token}}
          MODRINTH_TOKEN: ${{steps.get-secrets.outputs.modrinth_token}}
          CLOUDFLARE_S3_ENDPOINT: ${{steps.get-secrets.outputs.cloudflare_s3_endpoint}}
          R2_ACCESS_KEY: ${{steps.get-secrets.outputs.cloudflare_access_key}}
          R2_SECRET_KEY: ${{steps.get-secrets.outputs.cloudflare_secret_key}}
          VERSION_FUNCTION_ENDPOINT: ${{ secrets.GCP_VERSION_FUNCTION_ENDPOINT }}
          SERVICE_ACCOUNT: ${{ secrets.GCP_FUNCTION_EXECUTION_ACCOUNT }}
          MAVEN_USERNAME: ${{steps.get-secrets.outputs.repolisite-publisher-name}}
          MAVEN_PASSWORD: ${{steps.get-secrets.outputs.repolisite-publisher-password}}
      - name: Verify Build Files
        if: inputs.enable_signature_check
        run: |
          for f in $(find ./ -name "*.asc") ; do
            echo "::group::${f:0:-4}"
            gpg --verify "$f" "${f:0:-4}"
            echo "::endgroup::"
          done
      - name: Verify Main Jar
        if: inputs.enable_signature_check
        run: |
          for f in $(find . ! -name '*deobf.jar' ! -name '*sources.jar' ! -name '*common.jar' ! -name '*dev.jar' ! -path '*/common/*' -path '*/build/libs/*' -name '*.jar') ; do
          echo "::group::Jar sign ${f}"
          jarsigner -verify -keystore "${{ steps.tmp-dir.outputs.path }}/kotori316_keystore.jks" "$f"
          echo "::endgroup::"
          done
      - name: Verify Maven Local
        if: inputs.enable_signature_check
        run: |
          for f in $(find ~/.m2 -name "*.asc") ; do
            echo "::group::${f:0:-4}"
            gpg --verify "$f" "${f:0:-4}"
            echo "::endgroup::"
          done
      - name: Get repository name
        if: always()
        id: repo-name
        run:
          echo "repo-name=$(basename "$REPO")" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}
      - name: Create Temporary Directory for build files
        id: build-files-tmp-dir
        run: |
          TMP_DIR="$(mktemp -d)"
          echo "path=${TMP_DIR}" >> "$GITHUB_OUTPUT"
      - name: Check main files
        id: main-files
        run: |
          find . ! -name '*deobf.jar' ! -name '*sources.jar' ! -name '*common.jar' ! -name '*dev.jar' ! -path '*/common/*' -path '*/build/libs/*' -name '*.jar' \
            -exec mv -t "${{ steps.build-files-tmp-dir.outputs.path }}" {} +
          ls "${{ steps.build-files-tmp-dir.outputs.path }}"
      - name: Attestation
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: '${{ steps.build-files-tmp-dir.outputs.path }}/*'
          subject-name: ${{ steps.repo-name.outputs.repo-name }}-Release-${{ github.run_number }}
      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.repo-name.outputs.repo-name }}-Release-${{ github.run_number }}
          retention-days: 7
          path: |
            **/build/*libs/
      - name: Upload maven
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.repo-name.outputs.repo-name }}-Maven-${{ github.run_number }}
          retention-days: 1
          # Required to upload files in ".m2" dir
          include-hidden-files: true
          path: ~/.m2
      - name: Cleanup Temporary Directory
        if: always()
        run: |
          rm -rf "${{ steps.tmp-dir.outputs.path }}"
          rm -rf "${{ steps.build-files-tmp-dir.outputs.path }}"
